-- DML statements

DELETE FROM public.CP_TYPE_DOCUMENT;

INSERT INTO CP_TYPE_DOCUMENT (TYP_DOC_CODE, DESCRIPCION)
VALUES ('001', 'DNI');

INSERT INTO CP_TYPE_DOCUMENT (TYP_DOC_CODE, DESCRIPCION)
VALUES ('002', 'Carnet de Extranjeria');
INSERT INTO CP_TYPE_DOCUMENT (TYP_DOC_CODE, DESCRIPCION)
VALUES ('003', 'Pasaporte');